// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/carsi-widget/WidgetList.tsx": () => import("../components/mockups/carsi-widget/WidgetList.tsx"),
  "./components/mockups/carsi-widget/WidgetStrip.tsx": () => import("../components/mockups/carsi-widget/WidgetStrip.tsx")
};
