// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/carsi-widget/CapsuleDark.tsx": () => import("../components/mockups/carsi-widget/CapsuleDark.tsx"),
  "./components/mockups/carsi-widget/CapsuleLight.tsx": () => import("../components/mockups/carsi-widget/CapsuleLight.tsx"),
  "./components/mockups/carsi-widget/CurrencyHome.tsx": () => import("../components/mockups/carsi-widget/CurrencyHome.tsx"),
  "./components/mockups/carsi-widget/CurrencyHomeV2Dark.tsx": () => import("../components/mockups/carsi-widget/CurrencyHomeV2Dark.tsx"),
  "./components/mockups/carsi-widget/CurrencyHomeV2Light.tsx": () => import("../components/mockups/carsi-widget/CurrencyHomeV2Light.tsx"),
  "./components/mockups/carsi-widget/GoldHome.tsx": () => import("../components/mockups/carsi-widget/GoldHome.tsx"),
  "./components/mockups/carsi-widget/GoldHomeV2Dark.tsx": () => import("../components/mockups/carsi-widget/GoldHomeV2Dark.tsx"),
  "./components/mockups/carsi-widget/GoldHomeV2Light.tsx": () => import("../components/mockups/carsi-widget/GoldHomeV2Light.tsx"),
  "./components/mockups/carsi-widget/NotifShellA.tsx": () => import("../components/mockups/carsi-widget/NotifShellA.tsx"),
  "./components/mockups/carsi-widget/NotifShellB.tsx": () => import("../components/mockups/carsi-widget/NotifShellB.tsx"),
  "./components/mockups/carsi-widget/NotifShellC.tsx": () => import("../components/mockups/carsi-widget/NotifShellC.tsx"),
  "./components/mockups/carsi-widget/OnboardingFlow.tsx": () => import("../components/mockups/carsi-widget/OnboardingFlow.tsx"),
  "./components/mockups/carsi-widget/PulseDark.tsx": () => import("../components/mockups/carsi-widget/PulseDark.tsx"),
  "./components/mockups/carsi-widget/PulseLight.tsx": () => import("../components/mockups/carsi-widget/PulseLight.tsx"),
  "./components/mockups/carsi-widget/SettingsScreen.tsx": () => import("../components/mockups/carsi-widget/SettingsScreen.tsx"),
  "./components/mockups/carsi-widget/WidgetList.tsx": () => import("../components/mockups/carsi-widget/WidgetList.tsx"),
  "./components/mockups/carsi-widget/WidgetStrip.tsx": () => import("../components/mockups/carsi-widget/WidgetStrip.tsx"),
  "./components/mockups/carsi-detail/AltinDetail.tsx": () => import("../components/mockups/carsi-detail/AltinDetail.tsx"),
  "./components/mockups/carsi-detail/UsdDetail.tsx": () => import("../components/mockups/carsi-detail/UsdDetail.tsx")
};
